base_url = "https://mslicer.com"
title = "mslicer"
description = "A high-performance, open-source slicer for MSLA resin printers. Compatible with printers that support any of the following file formats: Chitu (.ctb), Elegoo (.goo), or NanoDLP (.nanodlp)."
author = "Connor Slade"

minify_html = true
generate_feeds = true
compile_sass = true

[markdown]
[markdown.highlighting]
theme = "min-light"

[extra]
commit = ""

# Latest release
version = "0.9.0"
release-date = "August 26th, 2026"
