base_url = "https://mslicer.com"
title = "mslicer"
description = "A high-performance, open-source slicer for MSLA resin printers."
author = "Connor Slade"

minify_html = true
generate_feeds = true
compile_sass = true

[markdown]
[markdown.highlighting]
theme = "min-light"

[extra]
commit = ""

# Latest release
version = "0.8.0"
release-date = "June 30th, 2026"
